# [colors.primary]
# foreground = "#e0def4"
# background = "#232136"
# dim_foreground = "#908caa"
# bright_foreground = "#e0def4"
#
# [colors.cursor]
# text = "#e0def4"
# cursor = "#56526e"
#
# [colors.vi_mode_cursor]
# text = "#e0def4"
# cursor = "#56526e"
#
# [colors.search.matches]
# foreground = "#908caa"
# background = "#393552"
#
# [colors.search.focused_match]
# foreground = "#232136"
# background = "#ea9a97"
#
# [colors.hints.start]
# foreground = "#908caa"
# background = "#2a273f"
#
# [colors.hints.end]
# foreground = "#6e6a86"
# background = "#2a273f"
#
# [colors.line_indicator]
# foreground = "none"
# background = "none"
#
# [colors.footer_bar]
# foreground = "#e0def4"
# background = "#2a273f"
#
# [colors.selection]
# text = "#e0def4"
# background = "#44415a"
#
# [colors.normal]
# black = "#393552"
# red = "#eb6f92"
# green = "#3e8fb0"
# yellow = "#f6c177"
# blue = "#9ccfd8"
# magenta = "#c4a7e7"
# cyan = "#ea9a97"
# white = "#e0def4"
#
# [colors.bright]
# black = "#6e6a86"
# red = "#eb6f92"
# green = "#3e8fb0"
# yellow = "#f6c177"
# blue = "#9ccfd8"
# magenta = "#c4a7e7"
# cyan = "#ea9a97"
# white = "#e0def4"
#
# [colors.dim]
# black = "#6e6a86"
# red = "#eb6f92"
# green = "#3e8fb0"
# yellow = "#f6c177"
# blue = "#9ccfd8"
# magenta = "#c4a7e7"
# cyan = "#ea9a97"
# white = "#e0def4"
[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#928374"
blue = "#7daea3"
cyan = "#89b482"
green = "#a9b665"
magenta = "#d3869b"
red = "#ea6962"
white = "#dfbf8e"
yellow = "#e3a84e"

[colors.normal]
black = "#665c54"
blue = "#7daea3"
cyan = "#89b482"
green = "#a9b665"
magenta = "#d3869b"
red = "#ea6962"
white = "#dfbf8e"
yellow = "#e78a4e"

[colors.primary]
background = "#282828"
foreground = "#dfbf8e"

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 12.5

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "Space"
mode = "Vi|~Search"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Escape"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "I"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "I"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "C"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "Open"
key = "Return"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Up"
key = "K"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Down"
key = "J"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Left"
key = "H"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Right"
key = "L"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SemanticLeft"
key = "B"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SemanticRight"
key = "W"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SemanticRightEnd"
key = "E"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SearchForward"
key = "Slash"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SearchBackward"
key = "Slash"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchNext"
key = "N"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SearchPrevious"
key = "N"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchConfirm"
key = "Return"
mode = "Search|Vi"

[[keyboard.bindings]]
action = "SearchCancel"
key = "Escape"
mode = "Search"

[[keyboard.bindings]]
action = "SearchCancel"
key = "C"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "SearchHistoryPrevious"
key = "P"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "SearchHistoryNext"
key = "N"
mode = "Search"
mods = "Control"

[scrolling]
multiplier = 5

[window]
decorations = "full"
dynamic_padding = true
padding = { x = 0, y = 0 }
dynamic_title = true
option_as_alt = 'Both'
startup_mode = "Fullscreen"

[window.dimensions]
columns = 240
lines = 150
