#!/bin/sh
alias ls='eza --icons --git'
alias rgr='ranger'
alias vim='/opt/homebrew/bin/nvim'
alias cat='bat'

alias boo='ghostty +boo'

alias g='lazygit'
alias x='tmux'
alias xs='tmux-sessionizer'
alias p='pnpm'

alias weather='curl wttr.in'

# shellcheck disable=SC2139,SC2086
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

alias shutdown="shutdown now"

# shellcheck disable=SC2142
alias xev="xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf \"%-3s %s\n\", \$5, \$8 }'"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# systemd
alias list_systemctl="systemctl list-unit-files --state=enabled"

# For using zsh in different OS
# case "$(uname -s)" in
#
# Darwin)
# 	# echo 'Mac OS X'
# 	alias ls='ls -G'
# 	;;
#
# Linux)
# 	alias ls='ls --color=auto'
# 	;;
#
# CYGWIN* | MINGW32* | MSYS* | MINGW*)
# 	# echo 'MS Windows'
# 	;;
# *)
# 	# echo 'Other OS'
# 	;;
# esac
