#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
export HISTSIZE=1000000
export SAVEHIST=1000000
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"
export GOPATH="$HOME/.local/share/go"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export CHECKUPDATES_DB="/tmp/checkup-db-100"

# Vars needed for japanese input
export XMODIFIERS='@im=fcitx'
export GTK_IM_MODULE='fcitx'
export QT_IM_MODULE='fcitx'

# export PATH="$PATH:./node_modules/.bin"
