#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
export HISTSIZE=1000000
export SAVEHIST=1000000
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"
export GOPATH="$HOME/.local/share/go"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export OPENAI_API_KEY="$(cat /home/scott/.config/nvim/.openApiKey)"
# export PATH="$PATH:./node_modules/.bin"
# eval "$(fnm env)"
# eval "`pip completion --zsh`"
