#!/bin/sh
alias ls='eza --icons --git'
alias lsa='eza -a --icons --git'
alias rgr='ranger'
alias vim='/usr/bin/nvim'
# alias vimrc='cd /home/scott/.config/nvim/; vim'
alias cat='bat'
alias handbrake='ghb'
alias dev='~/.local/firefox-dev/firefox/firefox'
alias update-fnm='cargo install fnm -- --skip-shell'

alias m='ncmpcpp'
alias c='bat'
alias g='lazygit'
alias x='tmux'
alias xs='tmux-sessionizer'
alias b='acpi -b'
alias n='fnm use'
alias p='pnpm'

# alias youtube='firefox --new-window https://youtube.com'
alias weather='curl wttr.in'

alias headphones='bluetoothctl connect FC:E8:06:63:49:81'

# shellcheck disable=SC2139,SC2086
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias syrinscape='$HOME/syrinscape/Syrinscape\ Online\ Player/Syrinscape\ Online\ Player'

alias shutdown="shutdown now"

# shellcheck disable=SC2142
alias xev="xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf \"%-3s %s\n\", \$5, \$8 }'"

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# systemd
alias list_systemctl="systemctl list-unit-files --state=enabled"

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# Launch School ESLint command
alias install-eslint="npm install eslint@7.12.1 eslint-cli babel-eslint --save-dev"

# For using zsh in different OS
# case "$(uname -s)" in
#
# Darwin)
# 	# echo 'Mac OS X'
# 	alias ls='ls -G'
# 	;;
#
# Linux)
# 	alias ls='ls --color=auto'
# 	;;
#
# CYGWIN* | MINGW32* | MSYS* | MINGW*)
# 	# echo 'MS Windows'
# 	;;
# *)
# 	# echo 'Other OS'
# 	;;
# esac
