[theme]
background = "default"
primary = "#dfbf8e"
secondary = "light black"
title = "#89b482"
playing = "#a9b665"
playing_bg = "#383838"
playing_selected = "#e78a4e"
highlight = "#d3869b"
highlight_bg = "#383838"
error = "#fbf1c7"
error_bg = "#ea6962"
statusbar_progress = "#7daea3"
statusbar_bg = "#282828"
statusbar = "#e3a84e"
cmdline = "#d5c4a1"
cmdline_bg = "#383838"
search_match = "#e3a84e"
